language: node_js
node_js:
  - "0.10"
install:
  - npm install
  - npm install -g coveralls
  - npm install -g mocha-lcov-reporter
script:
  - grunt test
after_success:
  - cat mochacov.lcov | coveralls.js
